-- OTA frontend releases for the Android WebView wrapper.
-- Only active releases are readable from the public client role.
-- Writes remain restricted to database administrators/service-side tooling.

create table if not exists public.app_releases (
  id bigint generated by default as identity primary key,
  version_code integer not null unique check (version_code > 0),
  version text not null check (char_length(trim(version)) between 1 and 30),
  html text not null,
  sha256 text not null check (sha256 ~ '^[0-9a-fA-F]{64}$'),
  release_notes text not null default '',
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.app_releases enable row level security;

revoke all on table public.app_releases from anon, authenticated;
grant select on table public.app_releases to anon, authenticated;

drop policy if exists app_releases_read_active on public.app_releases;
create policy app_releases_read_active
on public.app_releases
for select
to anon, authenticated
using (is_active = true);

create index if not exists idx_app_releases_active_version
on public.app_releases (version_code desc)
where is_active = true;
