name: Export Android APK Signer

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android 36 build tools
        run: sdkmanager "build-tools;36.0.0"

      - name: Upload apksigner jar
        uses: actions/upload-artifact@v4
        with:
          name: android-apksigner-tool
          path: ${{ env.ANDROID_HOME }}/build-tools/36.0.0/lib/apksigner.jar
